codeql:
  cli_path: "C:/Users/MAXRAGE/Downloads/codeql-bundle-win64/codeql/codeql.exe"
  languages:
    - python
    - java
    - javascript
  default_query_suites:
    python: "python-security-and-quality.qls"
    java: "java-security-and-quality.qls"
    javascript: "javascript-security-and-quality.qls"

repositories:
  - url: "https://github.com/maxrage2529/chatbot"
    branch: "develop"
    languages: ["python"]

    # - url: "https://github.com/maxrage2529/sample-vulnerabilities"
    #   branch: "python"
    #   languages: ["python"]

    # - url: "https://github.com/maxrage2529/sample-vulnerabilities"
    #   branch: "java"
    #   languages: ["java"]

    # - url: "https://github.com/maxrage2529/sample-vulnerabilities"
    #   branch: "javascript"
    #   languages: ["javascript"]

  # - url: "https://github.com/maxrage2529/sample-vulnerabilities"
  #   branch: "py-js"
  #   languages: ["python", "javascript"]

output:
  results_dir: "./results"
  log_dir: "./logs"